// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DataMasking
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("masked")]
        public string Masked { get; set; }

        [JsonProperty("detected")]
        public Detected Detected { get; set; }
    }

    public partial class Detected
    {
        [JsonProperty("email")]
        public long Email { get; set; }

        [JsonProperty("phone")]
        public long Phone { get; set; }

        [JsonProperty("ssn")]
        public long Ssn { get; set; }

        [JsonProperty("credit_card")]
        public long CreditCard { get; set; }

        [JsonProperty("ip_address")]
        public long IpAddress { get; set; }

        [JsonProperty("url")]
        public long Url { get; set; }

        [JsonProperty("date")]
        public long Date { get; set; }
    }
}
